apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-oomf
  namespace: burrzinga-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:72cd7fa203496fd7a3ebc1da457a7da82ad5fdffcb3de56c6fe1fb9c5e5575f6
        name: my-java-quarkus
        resources: {}
status: {}
