apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oomf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-oomf
    app.kubernetes.io/part-of: samq
  name: devfile-sample-code-with-quarkus-oomf
  namespace: burrzinga-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oomf
status:
  loadBalancer: {}
